[project]
name = "1-dataset-curation"
version = "0.1.0"
description = "Curate 2022_Haghighi_NatureMethods"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.31.0",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
    "tabulate>=0.9.0",
]
